ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY (id);
ALTER TABLE AppUserAuth ADD CONSTRAINT AppUserAuth_pk PRIMARY KEY (id);
ALTER TABLE City ADD CONSTRAINT City_pk PRIMARY KEY (id);
ALTER TABLE Province ADD CONSTRAINT Province_pk PRIMARY KEY (id);
ALTER TABLE Country ADD CONSTRAINT Country_pk PRIMARY KEY (id);
ALTER TABLE Feedback ADD CONSTRAINT Feedback_pk PRIMARY KEY (id);
ALTER TABLE FeedbackAverage ADD CONSTRAINT FeedbackAverage_pk PRIMARY KEY (id);

ALTER TABLE LocationTrack ADD CONSTRAINT LocationTrack_pk PRIMARY KEY (id);
ALTER TABLE CellPhoneRegister ADD CONSTRAINT CellPhoneRegister_pk PRIMARY KEY (id);

ALTER TABLE UserProfile ADD CONSTRAINT UserProfile_pk PRIMARY KEY (id);
ALTER TABLE Orders ADD CONSTRAINT Orders_pk PRIMARY KEY (id);
ALTER TABLE travel ADD CONSTRAINT travel_pk PRIMARY KEY (id);
ALTER TABLE Dealing ADD CONSTRAINT Dealing_pk PRIMARY KEY (id);
ALTER TABLE Location ADD CONSTRAINT Location_pk PRIMARY KEY (id);

ALTER TABLE Receipt ADD CONSTRAINT Receipt_pk PRIMARY KEY (id);

ALTER TABLE UserAvatar ADD CONSTRAINT UserAvatar_pk PRIMARY KEY (id);

ALTER TABLE OrderAvatar ADD CONSTRAINT OrderAvatar_pk PRIMARY KEY (id);





