ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY (id);
ALTER TABLE AppUserAuth ADD CONSTRAINT AppUserAuth_pk PRIMARY KEY (id);
ALTER TABLE City ADD CONSTRAINT City_pk PRIMARY KEY (id);
ALTER TABLE Province ADD CONSTRAINT Province_pk PRIMARY KEY (id);
ALTER TABLE Country ADD CONSTRAINT Country_pk PRIMARY KEY (id);